name: ğŸš€ Deploy Static to S3

permissions:
  id-token: write # AWS OIDC í•„ìš”
  contents: read # repo ì²´í¬ì•„ì›ƒìš©

on:
  workflow_dispatch: {}
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    # PRì´ merge ë˜ì–´ closed ëì„ ë•Œë§Œ ì‹¤í–‰
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      # 1) ì†ŒìŠ¤ ì²´í¬ì•„ì›ƒ
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Node.js ì„¤ì¹˜
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3) ì˜ì¡´ì„± ì„¤ì¹˜
      - name: Install dependencies
        run: npm ci

      # 4) ì •ì  ë¹Œë“œ
      - name: Build
        run: npm run build

      # 5) AWS ìê²©ì¦ëª… ì„¤ì •
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 6) S3ì— ì—…ë¡œë“œ (ë™ê¸°í™” + ì‚­ì œ)
      - name: Sync to S3 Bucket
        run: |
          aws s3 sync out/ s3://${{ secrets.BUCKET_NAME }} \
            --delete
